# Generated by Django 3.1.5 on 2021-04-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='movies',
            field=models.ManyToManyField(related_name='movies', to='myapp.Movie'),
        ),
    ]
