# Generated by Django 3.1.5 on 2021-04-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210412_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='movies',
            field=models.ManyToManyField(related_name='actors', to='myapp.Movie'),
        ),
    ]
