# Generated by Django 3.1.5 on 2021-04-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210412_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='myapp.Cast'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='movies',
            field=models.ManyToManyField(to='myapp.Movie'),
        ),
    ]
